AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation service role used to create/update infra stacks."

Parameters:
  ProjectName:
    Type: String
    Default: microservices-lab
  Environment:
    Type: String
    Default: dev

Resources:
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-cfn-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  CloudFormationServiceRoleArn:
    Value: !GetAtt CloudFormationServiceRole.Arn
